version: "3.7"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /Users/raunogroch/Documents/torrentDownloads/appdata/config:/config
      - /Users/raunogroch/Documents/torrentDownloads/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    #restart: unless-stopped